### ISSUE TITLE
How to access rpc.sock and pub.sock

### ISSUE THREAD

**Issue by zerataul** [achingbrain/pm2-web#49]
Hi, everybody.

I implemented under the Multi- host.

config.json
I want to access to other server in path ~/.pm2/rpc.sock and ~/.pm2/pub.sock.

Do you know how people??
Can you teach me??

please, help me.

**Comment by achingbrain** [comment]
This seems like the same question as the other issue you opened, #48.  The answer is the same.  It is no longer supported.  If you want to monitor multiple hosts, you cannot do this with pm2.  Use [Guvnor](http://libraries.io/npm/guvnor) instead.
