### ISSUE TITLE
Run with nginx reverse proxy

### ISSUE THREAD

**Issue by nlaplante** [achingbrain/pm2-web#9]
Hi, I've been wondering how to run this behind an nginx reverse proxy. I got the web interface to run, but I don't know how to map the ws call with the proxy. Is this possible? Like with socket.io ? Port 9001 is closed publicly on my server.

**Comment by ghost** [comment]
@randomsock did you get the proxy working? Absolute URLs are bugging me too.

**Comment by randomsock** [comment]
@PavelVanecekGIC just tried again with pm2-web 2.1.3 and no it still doesn't work.

To clarify, you _should_ (haven't tried it) be able to reverse proxy it if you don't add a base path, like:

```
    location / {
            proxy_pass http://127.0.0.1:9000/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
    }
```

Though in practice you would probably want to use a DNS alias/subdomain and dedicate an nginx server block to that so it can still sit at root, eg `http://pm2web.mydomain.com`, then **:80/** proxies to **:9000/**.

But I don't want to do that, I manage a number of servers and just want to add a `/pm2` path to each in nginx, so `http://stuff.mydomain.com/pm2` proxies to **:9000/**

Maybe I should open a new issue for this ...
